### ISSUE TITLE
New version of dragon-boss AI stuck much often that previous

### ISSUE THREAD

**Issue by BlackLordRoo** [Archival1/CV-BugReporting#13] opened 2024-01-22 00:35 UTC
**Describe the bug**
Dragon stuck very often, especially at some places (like bathroom), after chasing and after respawn. He don't react of giraffe, kangaroo and interactable NPC, even when they was filled and at free roam mode. He stuck when his balls barely touch corners.

**To Reproduce**
1. Load level 'City'
2. Lure or grab dragon at unusual places / lure giraffe, kangaroo, or intreactable npc near to him / follow him when he try turn right after coner.
3. Balls stuck

**Expected behavior**
His AI Should have addition modes for use when not move long time of stuck in place.
Like, he should use similar to alarm system when using his visual detection behavior - if not seeing his npc tagret some time, he should to change it. He also needs free roaming mode. Or even better - using radius detect for traces of npc movement (like scent analogy) and trying to follow most recent traces until visual detection.
I hope his limited "diet" is just a bug - it was more fun before, when he was able to clear the whole map.
About his balls and corners - what if his balls not moving sometimes - it starts to shift left and right by itself. At least it solves problems with corners... his balls still stuck behind closed doors.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows
 - Graphics Card AMD 6600XT
 - Version cef91e5c

**Comment by RobotFailedCaptcha** [comment] 2024-01-22 17:07
This is two issues tied together. 

#1 after eating enough the dragon will just get stuck in places, and its hitbox(whatever you call it) will be much larger than it actually appears. The larger the hitbox the easier for it to get trapped. trying to drag it through doors or areas will show you why its getting stuck. Same thing as you eating too much and getting stuck in a corridor.

#2 The dragon will stop moving and just stand motionless. Not only the dragon but other NPCS as well. 

I think this happens because:

They are trying to path somewhere and cant find a valid path so just freeze in place (Meaning you take a dragon to the roof to feed it and it just stares blankly in the distance ignoring any npcs around it until it finds a valid path or the player)

![image (1)](https://github.com/Archival1/CV-BugReporting/assets/157373046/c9a93b54-e692-40a0-b7c7-d35f006107fb)
![image](https://github.com/Archival1/CV-BugReporting/assets/157373046/4064ea94-541e-4e88-b5c5-641138a0499b)

**Comment by Archival1** [comment] 2024-01-22 23:48
The dragons behaviour was altered in the patch so that they no longer go after every single NPC on the map and instead only targets those marked as being in the same group as them.

This was intended to stop them from trying to go after targets on the other side of the map that they couldn't possibly reach but it means they don't grab any and all NPC's so im planning to do another pass on them soon that will hopefully address that.

**Comment by Archival1** [comment] 2024-01-25 01:10
Update on the NPC comment - I've changed the dragon again so they should now be back to eating everyone but still will only go after the player based on detecting them.

As far as getting stuck is concerned there were no changes (and have been none so far) to the dragons pathfinding or physics so anything about them being stuck more often is likely just unlucky choices on their behalf.

**Comment by Archival1** [comment] 2024-02-18 03:17
Closing this as we don't have any intention of altering the pathfinding at this time, the dragon getting stuck on their own balls is something of a 'feature'.

**Closed as completed** 2024-02-18 03:16 UTC
