### ISSUE TITLE
Rat girls get stuck en masse in cafeteria of Level 4: Station

### ISSUE THREAD

**Issue by Seydaschu** [Archival1/CV-BugReporting#38] opened 2024-02-17 18:07 UTC
**Describe the bug**
In level 4, over time rat girls get stuck in the cafeteria instead of roaming the hallways.  They end up standing on counters and seats in the middle, as if they're trying to sit down but get stuck.

**To Reproduce**
1. Load level 4: Station
2. Play the game stealthily, do not alarm the rat girls in the halls
3. After some time, enter the cafeteria through the halls behind the kitchen
4. Many rat girls are colliding in the center, unable to leave

**Expected behavior**
Rat girls should be leaving the cafeteria and patrolling the hallways and other points of interest.

**Screenshots**
(https://github.com/Archival1/CV-BugReporting/assets/160342552/e2e5cba8-39e6-4c74-9f4d-3c66ad97e2f1)

**Comment by Archival1** [comment] 2024-02-18 02:44
Can't reproduce but can speculate why that might happen, moved chairs a tiny bit back to compensate

**Comment by BlackLordRoo** [comment] 2024-02-18 05:58
I have seen that bug often and it is quite easy to reproduce, just need much time for that. As I notice - that happens if rat sitting on specific places. After standing up, they become standing on table or chair, where can't able to create new waypoints for movements. They can't move even in alert mode, but if push them from table and chair - their AI will start to work again.

**Comment by Archival1** [comment] 2024-03-25 03:33
This should be fixed with the modding support update - I'm leaving this open for a few more days incase anyone runs into it again.

**Closed as completed** 2024-05-14 07:17 UTC
Labels: bug, Actioned
